### 
GET http://localhost:5000/api/users 


### 
POST http://localhost:5000/api/register HTTP/1.1
  content-type: application/json 

  {
    "username": "TomBradly",
    "password": "123456"
  }

### 
POST http://localhost:5000/api/login HTTP/1.1
  content-type: application/json 

  {
    "username": "TomBradly",
    "password": "123456"
  }

###
GET http://localhost:5000/api/logout HTTP/1.1
